version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_rails
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fast_msg_development
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails_app
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create db:migrate && bin/rails s -b 0.0.0.0"
    volumes:
      - .:/rails
      #- bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_HOST: db
      FAST_MSG_DATABASE_PASSWORD: root123

volumes:
  db_data:
  bundle_data: